# config file version
apiVersion: 1

# list of datasources to insert/update
# available in the database
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres-db.:5432
    database: monitor
    user: postgres
    secureJsonData:
      password: 'example'
    jsonData:
      sslmode: 'disable'